import { makeStyles } from '@material-ui/core';

export const useStyles = makeStyles((theme) => ({
  root: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginTop: theme.spacing(25),
  },

  content: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    // background: theme.palette.project.gray,
    background: '#2c2e32',
    width: '100%',
    borderRadius: '15px',
    maxWidth: '800px',
    padding: '10px 20px',
    marginTop: '20px',
    '& p': {
      color: 'white',
      fontSize: '1rem',
      padding: '5px 10px',
    },
    [theme.breakpoints.down('sm')]: {
      display: 'flex',
      width: '80%',
      flexDirection: 'column',
    },
  },
  description: {
    fontSize: '0.9rem',
    margin: theme.spacing(0.6),
    color: '#ededed',
  },
  unit1: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderRight: '1px solid #1d1e21',
    paddingRight: '20px',
    paddingLeft: '20px',
    color: 'white',
    '& div:first-child': {
      display: 'flex',
      alignItems: 'center',
      margin: theme.spacing(1),
      color: `#949494`,
      fontSize: '0.9rem',
    },
    '& div:nth-child(2)': {
      fontSize: '1.2rem',
      margin: theme.spacing(1),
      display: 'flex',
      alignItems: 'center',
    },
    '& img': {
      marginRight: '5px',
    },
    [theme.breakpoints.down('sm')]: {
      borderRight: 'none',
      borderBottom: '1px solid #1d1e21',
      paddingRight: '0',
      paddingLeft: '0',
      paddingBottom: '20px',
      alignItems: 'center',
    },
  },
  unit2: {
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid #1d1e21',
    alignItems: 'flex-start',
    paddingLeft: '20px',
    [theme.breakpoints.down('sm')]: {
      borderRight: 'none',
      borderBottom: '1px solid #1d1e21',
      paddingRight: '0',
      paddingBottom: '20px',
      paddingTop: '20px',
      alignItems: 'center',
      paddingLeft: '0',
    },
  },
  unit3: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingLeft: '15px',
    [theme.breakpoints.down('sm')]: {
      borderRight: 'none',
      paddingRight: '0',
      paddingBottom: '20px',
      paddingTop: '20px',
      paddingLeft: '0px',
      alignItems: 'center',
    },
  },
  stakeInput: {
    display: 'flex',
    justifyContent: 'center',
  },
  burnEstimation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    color: 'white',
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center',
    },
  },
  burnTextDiv: {
    marginTop: '35px',
  },
  burnTitle: {
    color: '#5d5d5d',
    marginBottom: '7px',
  },
  burnEstimationText: {
    fontSize: '1rem',
  },
  paperRoot: {
    padding: '5px 15px',
    display: 'flex',
    marginTop: theme.spacing(5),
    alignItems: 'center',
    width: 280,
    // background: theme.palette.project.background.secondary,
    borderRadius: '10px',
    border: '3px solid transparent',
    background: `linear-gradient(${theme.palette.project.background.secondary}, ${theme.palette.project.background.secondary}) padding-box,linear-gradient(0deg, #ff0060, #9e2fdb, #00aeff) border-box`,
    // borderImage: 'linear-gradient(0deg, #ff0060, #9e2fdb, #00aeff) 1',
  },
  input: {
    marginLeft: theme.spacing(1),
    color: 'white',
    fontSize: '1rem',
    flex: 1,
  },
  max: {
    borderRadius: '10px',
    border: '1px solid white',
    fontSize: '0.7rem',
    color: 'white',
    padding: '2px 10px',
    cursor: 'pointer',
  },
  icon: {
    margin: theme.spacing(1),
  },
  stakeBtn: {
    background: '#2bb07e !important',

    color: 'white !important',
    margin: theme.spacing(4),
    borderRadius: '10px',
    padding: '10px 20px',
    '&:hover': {
      background: '#2bb07e',
    },
  },
  stakeDiv: {
    borderTop: `1px solid ${theme.palette.project.gray}`,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  sliderDiv: {
    width: '70%',
    marginTop: theme.spacing(3),
    paddingTop: theme.spacing(2),
    display: 'grid',
    gridTemplateColumns: '6fr 1fr',
    alignItems: 'center',
    justifyContent: 'center',
    '&>div': {
      [theme.breakpoints.down('xs')]: {
        width: '100%',
      },
    },
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column',
      width: '100%',
      display: 'flex',
    },
  },
  tokenVolumn: {
    color: 'white',
    marginTop: '30px',
  },
  slider: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    [theme.breakpoints.down('sm')]: {
      width: '90%',
    },
  },
  stakeInfo: {
    color: 'white',
    fontSize: '0.9rem',
    marginRight: '10px',
    display: 'flex',
    alignItems: 'center',
    '& img': {
      margin: '0px 5px',
    },
    '& p': {
      fontSize: '1rem',
      fontWeight: '600',
    },
  },
  served: {
    color: '#687076',
    textTransform: 'uppercase',
  },
  eesBtn: {
    background: `linear-gradient(180deg, #ff887c, #e74878)`,
    display: `flex`,
    color: `white`,
    fontWeight: `700`,
    alignItems: `center`,
    borderRadius: `10px`,
    marginTop: '20px',
    width: '150px',
    fontSize: '0.75rem',
    '& img': {
      marginLeft: '5px',
      marginTop: '-2px',
    },
  },
  multi: {
    fontSize: '0.8rem',
    background: theme.palette.project.background.secondary,
    borderRadius: '10px',
    padding: '1px 10px',
    marginRight: '10px',
    '& p': {
      backgroundColor: `#f3ec78`,
      backgroundImage: `linear-gradient(180deg, #cf0fff, #a8c2ff);`,
      backgroundSize: `100%`,
      '-webkit-background-clip': 'text',
      '-moz-background-clip': 'text',
      '-webkit-text-fill-color': `transparent`,
      '-moz-text-fill-color': `transparent`,
    },
  },
}));
